on: push
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.actor }}/bot:latest
      - uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER }}
          username: student
          key: $ {{ secrets.SSH }}
          script: |
            echo ${{ secrets.PAT }} | docker login --username ${{ github.actor }} --password-stdin
            docker run ghcr.io/${{ github.actor }}/bot:latest      